# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VsBONe2biw4L8V8np5akvTwmo0GDaq45
"""

#creating my own data set
#amount spends in a span of a year

import numpy as np
import matplotlib.pyplot as plt
months = np.arange(1,13)
np.random.seed(35)
amount=np.random.randint(10000,120000,12)
amount=np.sort(amount)
print(months)
print(amount)

x=months.reshape(-1,1)
x

y=amount
y

plt.scatter(months,amount)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

y_pred=model.predict(x)
y_pred

y

model.predict([[3.5]])

plt.scatter(x,y)
plt.plot(x,y_pred,c='red')

model.coef_

model.intercept_

